CREATE DATABASE IF NOT EXISTS iiko;

USE iiko;

CREATE TABLE IF NOT EXISTS invoice (
    id INT UNSIGNED PRIMARY KEY auto_increment,
    number VARCHAR(255),
    status VARCHAR(255),
    date TIMESTAMP,
    discount INT,
    last_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS line (
    id INT UNSIGNED PRIMARY KEY auto_increment,
    name VARCHAR(255),
    amount DECIMAL(8,2),
    quantity INT UNSIGNED,
    invoice INT UNSIGNED,
    last_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);